version: '3.7'
services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: anidb
      POSTGRES_PASSWORD: test123

  testDatabase:
    image: postgres
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: anidbtest
      POSTGRES_PASSWORD: test123
